live_config_reload = true

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[font]
size = 17.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
blur = true
decorations = "buttonless"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 120
lines = 35

[env]
term = "xterm-256color"

# [colors.primary]
# background = "#000000"

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
# background = '#1a1b26'
# background = '#191724'
background = '#000000'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
